import { PortfolioItem } from './types';

export const portfolioData: PortfolioItem[] = [
  {
    category: 'tutorial',
    date: '2025-10-10',
    displayDate: 'Oct 2025',
    youtubeId: 'FDd-eLMpXmE',
    title: 'Blender: Stop objects flying away when you unparent',
    thumbnail: 'images/portfolio/blendertuto1.webp',
  },
  {
    category: 'tutorial',
    date: '2025-09-30',
    displayDate: 'Sep 2025',
    youtubeId: 'Yl22YEUcAQw',
    title: 'Unity 3D: Quick fix for Unity Scene lag',
    thumbnail: 'images/portfolio/unitytuto1.webp',
  },
  {
    category: 'tutorial',
    date: '2025-09-29',
    displayDate: 'Sep 2025',
    url: '/project/arduino-unity',
    title: 'Connect your Arduino to Unity 3D',
    thumbnail: 'images/tuto-arduino-unity/arduino.webp',
    mainProject: true
  },
  {
    category: 'publication',
    date: '2025-04-01',
    displayDate: 'Apr 2025',
    url: 'pdfs/paper5.pdf',
    period: 'In MDPI Virtual Worlds',
    title: 'Study of Visualization Modalities on Industrial Robot Teleoperation for Inspection in a Virtual Co-Existence Space',
    authors: '<strong class="text-blue-600">D Mazeas</strong>, B Namoano',
  },
  {
    category: 'teaching',
    date: '2025-02-01',
    displayDate: '2025 Spring',
    url: 'pdfs/HCI.pdf',
    title: 'AI3153 Human-Computer Interaction',
    period: 'BNBU',
    description: 'Class of 63 undergraduate students',
  },
  {
    category: 'teaching',
    date: '2025-02-01',
    displayDate: '2025 Spring',
    title: 'GCAP3123 Computer Technology and AI Project',
    period: 'BNBU',
    description: 'Class of 49 undergraduate',
  },
  {
    category: 'teaching',
    date: '2025-01-01',
    displayDate: '2025 Spring',
    title: 'GTSC2093 IT for Success in Everyday Life and Work',
    period: 'BNBU',
    description: 'Class of 75 undergraduate students',
  },
  {
    category: 'portfolio',
    date: '2025-01-01',
    displayDate: '2025',
    title: 'Human-Computer Interaction Course',
    subtitle: 'Teaching',
    url: '/project/hci-course',
    thumbnail: 'images/portfolio/thumbnails/Human-Computer Interaction Course.png',
    mainProject: true
  },
  {
    category: 'teaching',
    date: '2024-10-01',
    displayDate: '2024 Fall',
    title: 'GTSC2093 IT for Success in Everyday Life and Work',
    period: 'BNBU',
    description: 'Class of 89 undergraduate',
  },
  {
    category: 'employment',
    date: '2024-09-18',
    displayDate: 'Sep 2024',
    logo: 'images/logos/bnbu.webp',
    title: 'Lecturer in Computer Science and Technology at BNBU',
    period: 'BNBU (China) | 10 Months',
  },
  {
    category: 'portfolio',
    date: '2024-08-01',
    displayDate: '2024',
    title: 'Expert and Worker Remote Collaboration',
    subtitle: 'Research',
    url: '/project/remote-collab',
    thumbnail: 'images/portfolio/thumbnails/Expert and Worker Remote Collaboration.png',
    mainProject: true
  },
  {
    category: 'publication',
    date: '2024-08-01',
    displayDate: 'Aug 2024',
    url: 'pdfs/paper4.pdf',
    period: 'In CIRP Design Conference',
    title: 'Designing Immersive Tools for Expert and Worker Remote Collaboration',
    authors: 'SCM Galvis*, <strong class="text-blue-600">D Mazeas*</strong>, F Noel, JA Erkoyuncu (*Equal contribution)',
    mainProject: true,
    subtitle: 'Research Paper'
  },
  {
    category: 'publication',
    date: '2024-04-01',
    displayDate: 'Apr 2024',
    url: 'https://dspace.lib.cranfield.ac.uk/items/3d611b76-5604-4269-bd2b-e03835fcaad4',
    period: 'PhD Thesis',
    title: 'Key principles for assessing and implementing remote inspection with telexistence capability',
    subtitle: 'PhD Thesis.',
    authors: '<strong class="text-blue-600">D Mazeas</strong>',
  },
  {
    category: 'degree',
    date: '2024-04-01',
    displayDate: 'Apr 2024',
    logo: 'images/logos/cranfield.webp',
    title: 'PhD in Manufacturing',
    description: 'Cranfield University (UK) - Centre for Digital and Design Engineering',
  },
  {
    category: 'publication',
    date: '2023-05-01',
    displayDate: 'May 2023',
    url: 'pdfs/paper3.pdf',
    period: 'In IEEE VRW',
    title: 'Telexistence-based remote maintenance for marine engineers',
    authors: '<strong class="text-blue-600">D Mazeas</strong>, JA Erkoyuncu, F Noel',
  },
  {
    category: 'publication',
    date: '2023-02-01',
    displayDate: 'Feb 2023',
    url: 'pdfs/paper2.pdf',
    period: 'In IFIP PLM',
    title: 'A telexistence interface for remote control of a physical industrial robot via data distribution service',
    authors: '<strong class="text-blue-600">D Mazeas</strong>, JA Erkoyuncu, F Noel',
  },
  {
    category: 'portfolio',
    date: '2023-01-01',
    displayDate: '2023',
    title: 'Telexistence for Remote Marine Maintenance',
    subtitle: 'Research',
    url: '/project/remote-maintenance',
    thumbnail: 'images/portfolio/thumbnails/Telexistence for Remote Marine Maintenance.png',
    mainProject: true
  },
  {
    category: 'employment',
    date: '2022-08-01',
    displayDate: 'Oct 2022',
    logo: 'images/logos/gscop.webp',
    title: 'Visiting PhD Researcher',
    period: 'G-SCOP LAB (France) | 6 Months',
  },
  {
    category: 'portfolio',
    date: '2022-01-01',
    displayDate: '2022',
    title: 'VR Interface for Industrial Robotics',
    subtitle: 'Research',
    url: '/project/telexistence-interface',
    thumbnail: 'images/portfolio/thumbnails/VR Interface for Industrial Robotics.png',
    mainProject: true
  },
  {
    category: 'certification',
    date: '2021-09-24',
    displayDate: 'Sep 2021',
    url: 'pdfs/certificate fanuc.pdf',
    logo: 'images/logos/fanuc.webp',
    title: 'Fanuc Robotics Standard Teach Pendant Programming (R30iB+ Controller)',
    description: 'FANUC',
  },
  {
    category: 'portfolio',
    date: '2021-01-01',
    displayDate: '2021',
    title: 'Industrial Robotics & Automation',
    subtitle: 'Training',
    url: '/project/industrial-robotics',
    thumbnail: 'images/portfolio/thumbnails/Industrial Robotics & Automation.png',
    mainProject: true
  },
  {
    category: 'employment',
    date: '2020-09-28',
    displayDate: 'Sep 2020',
    logo: 'images/logos/cranfield.webp',
    title: 'PhD Researcher at Cranfield University',
    period: 'Cranfield University (UK) | 3 Years',
  },
  {
    category: 'publication',
    date: '2020-06-01',
    displayDate: 'Jun 2020',
    url: 'pdfs/paper1.pdf',
    period: 'In DESIGN conference',
    title: 'IMPRO: Immersive prototyping in virtual environments for industrial designers',
    authors: 'S Stadler, H Cornet, <strong class="text-blue-600">D Mazeas*</strong>, JR Chardonnet, F Frenkler (*App development, experiment design, data collection, and analysis)',
  },
  {
    category: 'employment',
    date: '2020-03-01',
    displayDate: 'Mar 2020',
    logo: 'images/logos/safran.webp',
    title: 'Augmented Reality Engineer at Safran',
    period: 'SAFRAN (UK) | 6 Months',
  },
  {
    category: 'degree',
    date: '2019-09-01',
    displayDate: 'Sep 2019',
    logo: 'images/logos/artsetmetiers.svg',
    title: "Master's degree in Digital Mock-up and 3D Visualization",
    description: 'Arts et Metiers (France) - Institut de Chalon',
  },
  {
    category: 'employment',
    date: '2019-02-01',
    displayDate: 'Feb 2019',
    logo: 'images/logos/tumcreate.webp',
    title: 'Research Assistant at TUMCREATE',
    period: 'TUMCREATE (Singapore) | 6 Months',
  },
  {
    category: 'portfolio',
    date: '2019-01-01',
    displayDate: '2019',
    title: 'VR Application for Immersive Prototyping',
    subtitle: 'Research',
    url: '/project/vr-prototyping',
    thumbnail: 'images/portfolio/thumbnails/VR Application for Immersive Prototyping.png',
    mainProject: true
  },
  {
    category: 'portfolio',
    date: '2018-01-01',
    displayDate: '2018',
    title: 'Industrial VR Applications',
    subtitle: 'Projects',
    url: '/project/master-projects',
    thumbnail: 'images/portfolio/thumbnails/Industrial VR Applications.png',
    mainProject: true
  },
  {
    category: 'degree',
    date: '2017-07-01',
    displayDate: 'JUL 2017',
    logo: 'images/logos/poitiers.webp',
    title: "Professional Bachelor's degree in Computer-Aided Drafting & Design",
    description: 'University of Poitiers (France)',
  },
  {
    category: 'degree',
    date: '2016-06-01',
    displayDate: 'JUN 2016',
    logo: 'images/logos/tours.webp',
    title: "Associate's degree in Materials Engineering",
    description: 'University of Tours (France)',
  },
];